package constant

const baseUrl = "/api/singbox/"
const RouteAddUserToDirect = baseUrl + "addUserToDirect"
const RouteAddUserToHttp = baseUrl + "addUserToHttp"
const RouteAddUserToHysteria = baseUrl + "addUserToHysteria"
const RouteAddUserToHysteria2 = baseUrl + "addUserToHysteria2"
const RouteAddUserToMixed = baseUrl + "addUserToMixed"
const RouteAddUserToNaive = baseUrl + "addUserToNaive"
const RouteAddUserToRedirect = baseUrl + "addUserToRedirect"
const RouteAddUserToShadowsocksMulti = baseUrl + "addUserToShadowsocksMulti"
const RouteAddUserToShadowsocksRelay = baseUrl + "addUserToShadowsocksRelay"
const RouteAddUserToShadowtls = baseUrl + "addUserToShadowtls"
const RouteAddUserToSocks = baseUrl + "addUserToSocks"
const RouteAddUserTotProxy = baseUrl + "addUserTotProxy"
const RouteAddUserToTrojan = baseUrl + "addUserToTrojan"
const RouteAddUserToTuic = baseUrl + "addUserToTuic"
const RouteAddUserToTun = baseUrl + "addUserToTun"
const RouteAddUserToVmess = baseUrl + "addUserToVmess"
const RouteAddUserToVless = baseUrl + "addUserToVless"
const RouteAddVlessInbound = baseUrl + "addVlessInbound"
