name: Debug build

on:
  push:

jobs:
  cross:
    strategy:
      matrix:
        include:
          # linux
          - name: linux-amd64
            goos: linux
            goarch: amd64
            goamd64: v1

          - name: linux-arm64
            goos: linux
            goarch: arm64

          - name: darwin-amd64
            goos: darwin
            goarch: amd64
            goamd64: v1
      fail-fast: true
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      GOARM: ${{ matrix.goarm }}
      GOMIPS: ${{ matrix.gomips }}
      CGO_ENABLED: 0
      TAGS: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_v2ray_api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get latest go version
        id: version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22

      - name: Build
        id: build
        run: make build

      - name: Rename build file unix
        if: matrix.goos != 'windows'
        run: mv sing-box sing-box-${{ matrix.name }}
      - name: Upload binaries to release
        if: matrix.goos != 'windows'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sing-box-${{ matrix.name }}
          tag: ${{ github.ref }}
          file_glob: true

      - name: Rename build file windows
        if: matrix.goos == 'windows'
        run: mv sing-box.exe sing-box-${{ matrix.name }}.exe
      - name: Upload binaries to release
        if: matrix.goos == 'windows'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sing-box-${{ matrix.name }}.exe
          tag: ${{ github.ref }}
          file_glob: true

